import "./globals.css";
import { Bagel_Fat_One, Nanum_Gothic } from "next/font/google";

export const fat = Bagel_Fat_One({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const nanum = Nanum_Gothic({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Day POP",
  description: "Generated by joo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={nanum.className}>
      <body>{children}</body>
    </html>
  );
}
