import Header from "@/components/header";
import "./globals.css";
import { Bagel_Fat_One, Nanum_Gothic } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Modal from "@/components/modal";
import MyPage from "@/components/mypage";

export const fat = Bagel_Fat_One({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-fat",
});

export const nanum = Nanum_Gothic({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nanum",
});

const metadata = {
  title: "Day POP",
  description: "Generated by joo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={nanum.className}>
      <body>
        <StoreProvider>
          <Modal></Modal>
          <MyPage />
          <Header />
          <main>{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
